### PR TITLE
ignore blocks of code - fixes #27

### LINKED ISSUE #27: How to ignore blocks of code
Istanbul has `/* istanbul ignore next */`. Whats the ibrik way of doing it? Or is that even supported?

### PR DESCRIPTION
**Pull request by Zolmeister**
note: need to build before testing
Also, technically the only esprima option needed was `comment` but added the others just in case istanbul decides to use them

### CODE REVIEW

**Comment by Zolmeister** [comment]
@Constellation should I build so the Travis passes?

**Comment by Zolmeister** [comment]
@Constellation bump

**Comment by Constellation** [comment]
Could you fix the failed tests?

**Comment by Zolmeister** [comment]
@Constellation The tests failed because of the way travis is set-up. I would recommend that the test-suite run a local build before executing, so that commits do not have to run the build themselves and dirty the git history.

Fixed

**Comment by Constellation** [comment]
LGTM

**Comment by Constellation** [comment]
Merged. Thank you!

**Pull request merged**
